spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket_ms?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
    username: root
    password: 123456
    # 连接池具体配置
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 15

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.software.demo.entity.po
logging:
  level:
    com.software.demo.dao: debug


